version: '3'
services:
  kafka-zookeeper:
    image: johnnypark/kafka-zookeeper
    container_name: kafka-zookeeper
    environment:
      - CONTAINER_ENV=dev
      - ADVERTISED_HOST=kafka-zookeeper
      - AUTO_CREATE_TOPICS=true

  springboot-kafka:
    build: .
    image: springboot-kafka
    container_name: springboot-kafka
    environment:
      - CONTAINER_ENV=dev
    ports:
      - "8086:8080"
