version: '3'
services:
  doku-kafka.apple-s-au.svc:
    image: johnnypark/kafka-zookeeper
    container_name: doku-kafka.apple-s-au.svc
    environment:
      - CONTAINER_ENV=dev
      - ADVERTISED_HOST=doku-kafka.apple-s-au.svc
      - AUTO_CREATE_TOPICS=true

  springboot-kafka:
    build: .
    image: springboot-kafka
    container_name: springboot-kafka
    environment:
      - CONTAINER_ENV=dev
    ports:
      - "8086:8080"
